res_filepath = "Results/Res/"
objective_values_filepath = "Results/Objectives/"
solutions_filepath = "Results/Solutions/"
paths_filepath = "Results/Paths/"
animations_filepath = "Results/Animations/"
runtimes_filepath = "Results/Runtimes/"
# matlab_filepath = "/Users/kadircan/Documents/MATLAB/Thesis/PathResults/"